### ISSUE TITLE
Isssue with Elastic Search

### ISSUE THREAD

**Issue by Untuouchum** [twintproject/twint-docker#1]
Hi !!
After these commands without error ES seems not launched.
docker-compose build
docker-compose up -d elasticsearch kibana
==> ALL 2 OK !

then , while doing : "docker-compose run -v $PWD/twint:/srv/twint twint {{CMD TWINT}}" :
==> ERROR :
elasticsearch.exceptions.ConnectionError: ConnectionError(<urllib3.connection.HTTPConnection object at 0x7f6c7452af60>: Failed to establish a new connection: [Errno 111] Connection refused) caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f6c7452af60>: Failed to establish a new connection: [Errno 111] Connection refused)

ES seems not launched /listening.
==> nothing on  "http://localhost:9200/twinttweets"

**Comment by fkztw** [comment]
@Untuouchum Add `-es twint_elasticsearch:9200'` as an option of `{{CMD TWINT}}`.
The default value is `localhost:9200`, but this won't work. Inside the docker-compose environment, it uses container name as hostname for the containers under the same docker network. You can use `docker ps` to check the name of container. In this case, the default container name of the elasticsearch container which created by the command `docker-compose up -d elasticsearch kibana` is "twint_elasticsearch".

**Comment by ghost** [comment]
should be solved with the new version

**Comment by natterstefan** [comment]
Hi @x0rzkov,

the issue still exists. The README says in the "Output Tweets to Elasticsearch" section:

```
docker-compose run -v $PWD/twint:/opt/app/data twint -u username -es localhost:9200
```

Where it should say

```
docker-compose run -v $PWD/twint:/opt/app/data twint -u username -es twint-elastic:9200
```

instead. I'll create a PR to improve that.
